src/EcomWeb/EcomWeb.WebApp/Models/ErrorViewModel.cs
using System;

namespace EcomWeb.WebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

src/EcomWeb/EcomWeb.WebApp/ViewModels/CategoryViewModel.cs
using EcomWeb.Contracts.Dtos;
using EcomWeb.Bussiness.Interfaces.Service;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EcomWeb.WebApp.ViewModels
{
    public class CategoryViewModel
    {
        public CategoryDto categoryDto{ get; set; }

        public IEnumerable<ProductDto> productDtos{ get; set; }
    }
}

src/EcomWeb/EcomWeb.WebApp/ViewModels/OrderViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using EcomWeb.Contracts.Dtos;
namespace EcomWeb.WebApp.ViewModels
{
    public class OrderViewModel
    {
        public IEnumerable<ShoppingCartItemDto> CartItemDtos{ get; set; }

        public OrderDto orderDto{ get; set; }
    }
}

src/EcomWeb/EcomWeb.WebApp/Controllers/CategoryController.cs
using EcomWeb.Bussiness.Interfaces;
using EcomWeb.Bussiness.Interfaces.Service;
using EcomWeb.Contracts.Dtos;
using EcomWeb.WebApp.ViewModels;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace EcomWeb.WebApp.Controllers
{
    public class CategoryController : Controller
    {
        private readonly ICategoryService _categoryService;
        private readonly IProductService _productService;
        public CategoryController(ICategoryService categoryService, IProductService productService)
        {
            _categoryService = categoryService;
            _productService = productService;
        }
        // GET: CategoryController
        [HttpGet]
        [Route("[controller]/[action]/{id?}")]
        public ActionResult Details(Guid id)
        {
            var categoryViewModel = new CategoryViewModel() 
            {
                categoryDto = _categoryService.GetByIdAsync(id).Result,
                productDtos = _productService.GetAllByIdParentAsync(id).Result
            };

            return View(categoryViewModel);
        }
    } 
}

src/EcomWeb/EcomWeb.WebApp/Controllers/HomeController.cs
using EcomWeb.Bussiness.Interfaces;
using EcomWeb.Bussiness.Interfaces.Service;
using EcomWeb.WebApp.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace EcomWeb.WebApp.Controllers
{
    public class HomeController : Controller
    {

        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger, IProductService productService)
        {
            _logger = logger;
        }
        [HttpGet]
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }

        public IActionResult Logout()
        {
            return SignOut("Cookies", "oidc");
        }
    }
}

src/EcomWeb/EcomWeb.WebApp/ViewComponents/CategoryMenuViewComponent.cs
using EcomWeb.Bussiness.Interfaces.Service;
using Microsoft.AspNetCore.Mvc;
using System.Threading.Tasks;

namespace EcomWeb.WebApp.ViewComponents
{
    public class CategoryMenuViewComponent : ViewComponent
    {
        private readonly ICategoryService _categoryService;


        public CategoryMenuViewComponent(ICategoryService categoryService)
        {
            _categoryService = categoryService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var res = await _categoryService.GetAllAsync();

            return View(res);
        }
    }
}

src/EcomWeb/EcomWeb.WebApp/ViewComponents/ProductFeaturedViewComponent.cs
using EcomWeb.Bussiness.Interfaces.Service;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections;
using System.Threading.Tasks;

namespace EcomWeb.WebApp.ViewComponents
{
    public class ProductFeaturedViewComponent : ViewComponent
    {

        private readonly IProductService _productService;


        public ProductFeaturedViewComponent(IProductService productService)
        {
            _productService = productService;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            var res = await _productService.GetAllFeaturedAsync();
            return View(res);
        }
    
    }
}

src/EcomWeb/EcomWeb.WebApp/Views/Category/Details.cshtml
@model EcomWeb.WebApp.ViewModels.CategoryViewModel;
@{

}
<link rel="stylesheet" href="~/css/product.css" />

<div class="text-center">
    <h1 class="display-4">@Model.categoryDto.Name</h1>
    <h4>@Model.categoryDto.Desc</h4>
</div>

<div class="row px-5 pt-5">
    @foreach (var product in Model.productDtos)
    {
        <div class="col-md-4 mt-4 mt-sm-0 mb-4 card-container">
            <div class="card text-center product p-4 pt-5 border-0 h-100 rounded-0">
                <img class="img-fluid d-block mx-auto" src="~/img/donut.png" alt="Command Hats Gear Image">
                <div class="card-body p-4 py-0 h-xs-440p">
                    <h5 class="card-title font-weight-semi-bold mb-3 w-xl-220p mx-auto">@product.Name</h5>
                    <p class="price">$@product.Price</p>
                </div>
                <p class="btn w-100 px-4 text-center mx-auto">
                    <input type="submit" class="btn btn-dark btn-lg w-100" name="add-button" value="Add to cart">
                </p>
            </div>
        </div>
    }
</div>

src/EcomWeb/EcomWeb.WebApp/Views/Home/Index.cshtml
@using EcomWeb.Contracts.Dtos;
@{
    var productFeatured = ViewData["productFeatured"] as List<ProductDto>;
}

<div class="text-center">
    <h1 class="display-4">Do you love Milk Tea?</h1>
    <h4>Order now!</h4>
</div>
<div class="alert alert-success">@await Component.InvokeAsync("CategoryMenu")</div>
<div>@await Component.InvokeAsync("ProductFeatured")</div>

src/EcomWeb/EcomWeb.WebApp/Views/Shared/Components/CategoryMenu/Default.cshtml
@model IEnumerable<EcomWeb.Contracts.Dtos.CategoryDto>
<h4>Category</h4>
<link rel="stylesheet" href="~/css/categoryMenu.css" />
<ul>
    @foreach (var category in Model)
    {
        <a class="category" asp-action ="Details" asp-controller="Category" asp-route-id="@category.Id">@category.Name</a>
    }
</ul>

src/EcomWeb/EcomWeb.WebApp/Views/Shared/Components/ProductFeatured/Default.cshtml
@model IEnumerable<EcomWeb.Contracts.Dtos.ProductDto>
<link rel="stylesheet" href="~/css/productFeatured.css"/>
<link rel="stylesheet" href="~/css/grid.css" />
<script src="~/js/grid.js"></script>
<h4>Product Featured</h4>

<div class="row px-5 pt-5">
    @foreach (var product in Model)
    {
        <div class="spe-prods mb-4 ">
            <div class="mainbox">
                <h3>@product.Name</h3>
                <img class="rotprod" src="img/donut.png" alt="">
            </div>
            <div class="price-big">
                <div>
                    <div class="floatting-price">
                        <h3>$@product.Price</h3>
                    </div>
                    <div class="month">
                        <p></p>
                    </div>
                </div>
                <div class="ordersection">
                    <a href="#" class="buybtn">Add to cart</a>
                </div>
            </div>
        </div>

       
    }

</div>

src/EcomWeb/EcomWeb.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - EcomWeb.WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-light border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Milk Tea Store</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">ShoppingCart</a>
                        </li>
                    </ul>
                </div>
             
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>